# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KubectlXctx < Formula
  desc "Execute kubectl commands across multiple contexts matching a regex"
  homepage "https://github.com/be0x74a/kubectl-xctx"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/be0x74a/kubectl-xctx/releases/download/v0.1.1/kubectl-xctx_0.1.1_darwin_amd64.tar.gz"
      sha256 "62ca2bb81b8db93c93a3ae67d94addc9706d6a1ed04c44b9f0142bddc9b235fa"

      def install
        bin.install "kubectl-xctx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/be0x74a/kubectl-xctx/releases/download/v0.1.1/kubectl-xctx_0.1.1_darwin_arm64.tar.gz"
      sha256 "e9203517f1973f823234f56d2d7061c5cbf871202e08b5a3fddb6dd2a98cd1a8"

      def install
        bin.install "kubectl-xctx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/be0x74a/kubectl-xctx/releases/download/v0.1.1/kubectl-xctx_0.1.1_linux_amd64.tar.gz"
      sha256 "dcecb974719c2af5a8a668d27af3c7d910260e576dab79e2377ad5923a5e510b"
      def install
        bin.install "kubectl-xctx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/be0x74a/kubectl-xctx/releases/download/v0.1.1/kubectl-xctx_0.1.1_linux_arm64.tar.gz"
      sha256 "6eb2e417fe8fcfe12fceb837ff43129452a492551b31d5ea07e45cbe56da09f1"
      def install
        bin.install "kubectl-xctx"
      end
    end
  end

  test do
    system "#{bin}/kubectl-xctx", "--version"
  end
end
