# This cask is auto-generated by GoReleaser on each release of kubectl-xctx.
# Do not edit manually — changes will be overwritten on the next release.
cask "kubectl-xctx" do
  version :latest
  desc "Execute kubectl commands across multiple contexts matching a regex"
  homepage "https://github.com/be0x74a/kubectl-xctx"
end
