# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubectl-xctx" do
  name "kubectl-xctx"
  desc "Execute kubectl commands across multiple contexts matching a regex"
  homepage "https://github.com/be0x74a/kubectl-xctx"
  version "0.1.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubectl-xctx"

  on_macos do
    on_intel do
      url "https://github.com/be0x74a/kubectl-xctx/releases/download/v#{version}/kubectl-xctx_#{version}_darwin_amd64.tar.gz"
      sha256 "2297a901339dd3d4cbe24db9a091721fe33b3454c9bf1ed4a6d89b28db3aa29a"
    end
    on_arm do
      url "https://github.com/be0x74a/kubectl-xctx/releases/download/v#{version}/kubectl-xctx_#{version}_darwin_arm64.tar.gz"
      sha256 "2a6eb930afde5cd97b4564fb9068ac4cada70016a30854c207049b3e84f4562b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/be0x74a/kubectl-xctx/releases/download/v#{version}/kubectl-xctx_#{version}_linux_amd64.tar.gz"
      sha256 "ab16c60a86e44fb9e15cad4f7c0756398f73275164ce9bb0c96b523cb87bdb8f"
    end
    on_arm do
      url "https://github.com/be0x74a/kubectl-xctx/releases/download/v#{version}/kubectl-xctx_#{version}_linux_arm64.tar.gz"
      sha256 "f3f1cc07b544cf61b56121279d2009ed2f1d2150d7b1a9d8435fa0375b1d1a48"
    end
  end

  # No zap stanza required
end
