# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubectl-xctx" do
  name "kubectl-xctx"
  desc "Execute kubectl commands across multiple contexts matching a regex"
  homepage "https://github.com/be0x74a/kubectl-xctx"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubectl-xctx"

  on_macos do
    on_intel do
      url "https://github.com/be0x74a/kubectl-xctx/releases/download/v#{version}/kubectl-xctx_#{version}_darwin_amd64.tar.gz"
      sha256 "f2b21dda8b078b74593072d3aaa6f5e6ee9fef07147412678551757db8945bca"
    end
    on_arm do
      url "https://github.com/be0x74a/kubectl-xctx/releases/download/v#{version}/kubectl-xctx_#{version}_darwin_arm64.tar.gz"
      sha256 "ef9fdc63a5a93941fd39c5024127ef01b3f3c6c72eace13354348b2b0e89b24d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/be0x74a/kubectl-xctx/releases/download/v#{version}/kubectl-xctx_#{version}_linux_amd64.tar.gz"
      sha256 "7727b47a25c8c56424473f82414ad3bcae406139764684b769cfdac7242e97b9"
    end
    on_arm do
      url "https://github.com/be0x74a/kubectl-xctx/releases/download/v#{version}/kubectl-xctx_#{version}_linux_arm64.tar.gz"
      sha256 "4b048acb9de689f2bb69fc3ee1b06eadc59e339d73f1e59924210b53b75d007d"
    end
  end

  # No zap stanza required
end
