# This formula is auto-generated by GoReleaser on each release of kubectl-xctx.
# Do not edit manually — changes will be overwritten on the next release.
class KubectlXctx < Formula
  desc "Execute kubectl commands across multiple contexts matching a regex"
  homepage "https://github.com/be0x74a/kubectl-xctx"
  version "0.0.0" # placeholder

  def install
    bin.install "kubectl-xctx"
  end

  test do
    system "#{bin}/kubectl-xctx", "--version"
  end
end
